import Head from 'next/head';
import Image from 'next/image';
import Button from '../components/Button/Button';
import styles from '../styles/Home.module.css';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>
        <div className="h-100">
          <div className="row h-100">
            <div className="col-xl-6 col-md-6 col-sm-12 d-flex justify-content-center flex-column">
              <h2 className={`${styles.title} pl-5`}>
                <span className={styles.autoconsume}>Autoconsumo </span>
                <span className={styles.solar}>Solar</span>
              </h2>

              <h2 className={`${styles.description} pl-5`}>
                Calcula, programa y ubica tu instalación.<br></br> Ahorra y optimiza cada día.
              </h2>
            </div>
            <div
              className={`${styles.imageHeader} col-xl-6 col-md-6 col-sm-12`}
              style={{ backgroundImage: "url(/img/solar_panel.jpeg)" }}
            >
            </div>
          </div>
        </div>
      </main>

      <section className="container">
        <div className="h-100">
          <div className={`${styles.section_1} row h-100 pt-5 pb-5`}>
            <div className="col-xl-6 col-md-6 col-sm-12 d-flex justify-content-center flex-column">
              <h2 className={styles.section_1_title}>
              Calcula <span className='c-primary'><i className="fas fa-bolt"></i> </span> optimiza
              </h2>

              <p className={`${styles.section_1_p} default-text c-gray-2`}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud.
              </p>
              <div className="pt-3">
              <Button type="primary" content="Contacta" ></Button>
              </div>

            </div>
            <div className="col-xl-6 col-md-6 col-sm-12 d-flex align-items-end justify-content-end">
              <Image
                width="500"
                height="500"
                alt="solar and energy"
                src="/img/sun_care.png"
                className={`${styles.section_1_img} w-100`}
              ></Image>
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
