import Head from 'next/head';
import Image from 'next/image';
import Button from '../components/Button/Button';
import Form from '../components/Form/Form';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main}`}>
        <div className="h-100">
          <div className="mx-auto row h-100">
            <div className="col-xl-6 col-md-6 col-sm-12 d-flex justify-content-center text-align-center flex-column">
              <h1 className={`${styles.title} pl-3 text-center`}>
                <span className={styles.autoconsume}>Autoconsumo </span>
                <span className={styles.solar}>Solar</span>
              </h1>

              <p className={`${styles.description} pl-3 text-center`}>
                Calcula, programa y ubica tu instalación.<br></br> Ahorra y optimiza cada día.
              </p>
              <div className="text-center mt-3">
                <Button type="primary" content="Contacta" ></Button>
              </div>

            </div>
            <div
              className={`${styles.imageHeader} col-xl-6 col-md-6 col-sm-12`}
              style={{ backgroundImage: "url(/img/solar_panel.jpeg)" }}
            >
            </div>
          </div>
        </div>
      </main>

      <section className="container">
        <div className="h-100">
          <div className={`${styles.section_1} row h-100 pt-5`}>
            <div className="col-xl-6 col-md-6 col-sm-12 d-flex justify-content-center flex-column">
              <h2 className={styles.section_1_title}>
                Calcula <span className='c-primary'><i className="fas fa-bolt"></i> </span> optimiza
              </h2>

              <p className={`${styles.section_1_p} default-text c-gray-2`}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud.
              </p>
              <div className="pt-3 text-sm-center">
                <Button type="primary" content="Contacta" ></Button>
              </div>

            </div>
            <div className="col-xl-6 col-md-6 col-sm-12 d-flex align-items-end justify-content-end">
              <Image
                width="500"
                height="500"
                alt="solar and energy"
                src="/img/sun_care.png"
                className={`${styles.section_1_img} w-100`}
              ></Image>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-app-primary" id="contact-form">
        <div className="mx-auto justify-content-center container p-5 mb-5">
          <p className={`${styles.section_1_p} default-text c-dark`}>
            «El principal problema con la energía solar en la superficie de
            la Tierra es que es tan intermitente, y aún no tenemos un almacenamiento decente».
          </p>
          <h4 className="c-dark">
            Stewart Brand.
          </h4>
        </div>
      </section>



      <section>
        <div className="container px-4 py-5" id="custom-cards">
          <h1 className="c-title pb-2 border-bottom border-app">Nuestra <b>filosofía</b></h1>

          <div className="row align-items-stretch g-4 py-5">

            <div className="col-sm-12 col-md-12 col-lg-4 mt-3">
              <div className="overflow-hidden text-white text-center mb-4">
                <Image
                  width="200"
                  height="200"
                  alt="solar and energy"
                  src="/img/solar-panel-icon.svg"
                  className="w-100"
                ></Image>
              </div>
              <div className="text-center">
                <h4 className="c-title">Energía a tope</h4>
                <p className="c-gray-2">El principal <b className="c-dark-1">problema</b> con la energía solar en la superficie de la Tierra es que es tan intermitente.</p>
              </div>
            </div>

            <div className="col-sm-12 col-md-12 col-lg-4 mt-3">
              <div className="overflow-hidden text-white text-center mb-4">
                <Image
                  width="200"
                  height="200"
                  alt="solar and energy"
                  src="/img/voltmeter.svg"
                  className="w-100"
                ></Image>
              </div>
              <div className="text-center">
                <h4 className="c-title">Energía a tope</h4>
                <p className="c-gray-2">El principal problema con la energía solar en la superficie de la Tierra es que es tan intermitente.</p>
              </div>
            </div>

            <div className="col-sm-12 col-md-12 col-lg-4 mt-3">
              <div className="overflow-hidden text-white text-center mb-4">
                <Image
                  width="200"
                  height="200"
                  alt="solar and energy"
                  src="/img/renewable.svg"
                  className="w-100"
                ></Image>
              </div>
              <div className="text-center">
                <h4 className="c-title">Energía a tope</h4>
                <p className="c-gray-2">El principal problema con la energía solar en la superficie de la Tierra es que es tan intermitente.</p>
              </div>
            </div>

          </div>
        </div>
      </section>


      <section id="contact-form">
        <div className="row mx-auto justify-content-center mb-5">
          <div className="col-xs-16 col-md-5 col-xl-5">
            <h2 className="mb-4">Contacto</h2>
            <div className='container'>
              <Form />
            </div>
          </div>
        </div>
      </section>
    </div>
  )
}
